# Safety Security and License Configuration file

security:
    # A severity number between 0 and 10. Some helpful reference points:
    # - 9=ignore all vulnerabilities except CRITICAL severity.
    # - 7=ignore all vulnerabilities except CRITICAL & HIGH severity.
    # - 4=ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity.
    ignore-cvss-severity-below: 0
    ignore-cvss-unknown-severity: False  # True or False. We recommend you set this to False.

    # Suppress non-zero exit codes when vulnerabilities are found.
    # Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities.
    # We recommend you set this to False.
    continue-on-vulnerability-error: False

    # Here you can list multiple specific vulnerabilities you want to ignore/exempt (optionally for a time period)
    # We recommend making use of the optional `reason` and `expires` keys for each vulnerability that you ignore.
    ignore-vulnerabilities:
        61601:  # https://data.safetycli.com/v/61601/f17
            reason: We can't upgrade to a newer version of Urllib3, see MAGIC/ops-data-store#29 for details
            expires: '2024-05-25'
        61893:  # https://data.safetycli.com/v/61893/f17
            reason: We can't upgrade to a newer version of Urllib3, see MAGIC/ops-data-store#29 for details
            expires: '2024-05-25'

# [Configuration for the `safety alert` command omitted as not used]
